# Generated by Django 3.1.7 on 2021-04-12 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('C', 'COMPLETE'), ('P', 'PENDING')], max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('precedence', models.CharField(choices=[('1', '1'), ('1', '1'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
